### ISSUE TITLE
Mod security: Blocked attempted read

### ISSUE THREAD

**Issue by harry-wood** [snowyu/minetest_yaml#1]
Setting up the quiz mod I got this error from mod security (Minetest 5.6.1)
```
ModError: Failed to load and run script from /Users/harrywood/Library/Application Support/minetest/mods/quiz/init.lua:
Mod security: Blocked attempted read from /Users/harrywood/Library/Application Support/minetest/mod_data/quiz/config.yml
stack traceback:
	[C]: in function 'open'
	.../Library/Application Support/minetest/mods/yaml/init.lua:44: in function 'readFile'
	.../Library/Application Support/minetest/mods/yaml/init.lua:72: in function 'readModDataConfig'
	.../Library/Application Support/minetest/mods/yaml/init.lua:109: in function 'readConfig'
	.../Library/Application Support/minetest/mods/quiz/init.lua:30: in main chunk
Check debug.txt for details.
```
I guess it means this needs updating to avoid doing file reads which upset mod security?  ...or maybe I'm just doing something wrong.

I did manage to hack it work by modifying [this line which sets 'modDataPath'](https://github.com/snowyu/minetest_yaml/blob/master/init.lua#L91). But I just crudely swapped it to 

`local modDataPath = WORLD_PATH .. filename`

**Comment by snowyu** [comment]
Sorry, it needs the PR: minetest/minetest#12315 to use the mod_data dir to storage instead the world dir.

Now, it should work.
